package com.ems.customdt;

public enum EmployeePosition {
	PROGRAMMER_ANALYST_TRAINEE, PROGRAMMER_ANALYST, ASSOCIATE, SENIOR_ASSOCIATE, MANAGER, SENIOR_MANAGER,
	ASSISTANT_DIRECTOR, DIRECTOR, SENIOR_DIRECTOR, AVP, VP, SVP, CTO, CIO, CEO
}
